"use client";
import { useEffect, useMemo, useState } from "react";
import { Search, RefreshCw, Save, GraduationCap } from "lucide-react";
import { Button } from "@/components/ui/button";

type App = Record<string, unknown>;
const labels: Record<string,string> = { filled: "Заполнил анкету", dropped: "Слетел", hold: "Холд", paid: "Выплачено" };
const date = (v: unknown) => v ? new Date(String(v)).toLocaleString("ru-RU", { day:"2-digit", month:"short", hour:"2-digit", minute:"2-digit" }) : "—";
export function CandidateCrm() {
  const [items, setItems] = useState<App[]>([]); const [selected, setSelected] = useState<App|null>(null); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [busy, setBusy] = useState(false); const [note, setNote] = useState("");
  const load = async () => { setBusy(true); try { const r = await fetch("/api/manager/applications", { cache:"no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error?.message || "Не удалось загрузить заявки"); setItems(d.applications || []); } finally { setBusy(false); } };
  // Initial data is synchronized from the protected API after hydration.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load().catch(() => {}); }, []);
  const filtered = useMemo(() => items.filter((x) => { const s = String(x.leadStatus || "filled"); const hay = `${x.name} ${x.telegramUsername} ${x.phone} ${x.vacancyId}`.toLowerCase(); return (filter === "all" || s === filter) && hay.includes(query.toLowerCase()); }), [items, filter, query]);
  const update = async (patch: Record<string,unknown>) => { if (!selected) return; setBusy(true); try { const r = await fetch("/api/manager/applications", { method:"PATCH", headers:{"content-type":"application/json"}, body:JSON.stringify({ id:selected.id, ...patch }) }); const d=await r.json(); if (!r.ok) throw new Error(d.error?.message || "Ошибка сохранения"); setItems((old) => old.map((x) => x.id === selected.id ? d.application : x)); setSelected(d.application); } finally { setBusy(false); } };
  const status = String(selected?.leadStatus || "filled");
  return <section className="mt-8 rounded-[28px] border border-[#d7e4d6] bg-[#f7faf5] p-5 shadow-sm sm:p-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-emerald-700">UpHire · CRM</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em] text-slate-900">Заявки кандидатов</h2><p className="mt-2 text-sm text-slate-600">Обработка лидов, статусы, заметки и обучение в одном окне.</p></div><Button variant="outline" onClick={() => load()} disabled={busy}><RefreshCw className="mr-2 size-4" /> Обновить</Button></div>
    <div className="mt-6 flex flex-wrap gap-3"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Имя, username, телефон…" className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-3 text-sm" /></div><select value={filter} onChange={(e)=>setFilter(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">Все статусы</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-2">{filtered.length ? filtered.map((x)=><button key={String(x.id)} onClick={()=>{setSelected(x);setNote(String(x.managerNote||""));}} className={`w-full rounded-2xl border bg-white p-4 text-left transition hover:border-emerald-400 ${selected?.id===x.id?"border-emerald-500 ring-2 ring-emerald-100":"border-slate-200"}`}><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-slate-900">{String(x.name)}</strong><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-800">{labels[String(x.leadStatus||"filled")]}</span></div><div className="mt-2 text-xs text-slate-500">{x.telegramUsername ? `@${x.telegramUsername} · ` : ""}{String(x.phone)} · {date(x.createdAt)}</div></button>) : <div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">Заявок пока нет</div>}</div>
    {/* eslint-disable-next-line react-hooks/purity */}
    <div className="rounded-2xl border border-slate-200 bg-white p-5">{selected ? <><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-500">Заявка №{String(selected.id)}</p><h3 className="mt-1 text-xl font-bold">{String(selected.name)}</h3></div><span className="text-xs text-slate-500">{date(selected.createdAt)}</span></div><p className="mt-3 text-sm text-slate-600">{selected.telegramUsername ? `@${selected.telegramUsername}` : "Username не указан"} · {String(selected.phone)}</p><label className="mt-5 block text-xs font-semibold text-slate-600">Статус<select value={status} onChange={(e)=>update({status:e.target.value})} className="mt-1 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs leading-relaxed text-slate-600">Профессия: {String(selected.vacancyId)}<br/>Заявка висит: {Math.max(0,Math.floor((Date.now()-new Date(String(selected.createdAt)).getTime())/86400000))} дн.</div><label className="mt-4 block text-xs font-semibold text-slate-600">Заметка<textarea value={note} onChange={(e)=>setNote(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Комментарий менеджера…" /></label><Button className="mt-3 w-full" onClick={()=>update({note})} disabled={busy}><Save className="mr-2 size-4"/>Сохранить заметку</Button><Button variant="outline" className="mt-2 w-full" onClick={()=>update({trainingCourse:String(selected.vacancyId),trainingStartedAt:new Date().toISOString()})} disabled={busy}><GraduationCap className="mr-2 size-4"/>Отправить на обучение</Button></> : <div className="py-16 text-center text-sm text-slate-500">Выберите заявку, чтобы открыть карточку</div>}</div></div>
  </section>;
}
